#!/bin/bash
# Test script for ESC key pause menu functionality

echo "==================================="
echo "ESC Key Pause Menu Test Script"
echo "==================================="
echo ""
echo "This script will run the game and guide you through testing the ESC key fix."
echo ""
echo "IMPORTANT: Watch the console output for debug messages!"
echo ""
echo "Test Sequence:"
echo "1. Login to the game"
echo "2. Start or join a match"
echo "3. During gameplay, press ESC - you should see:"
echo "   - 'ESC key detected! isPaused=0'"
echo "   - 'Toggling pause state to: 1'"
echo "   - Pause menu appears with 'GAME PAUSED' text"
echo ""
echo "4. Press ESC again - you should see:"
echo "   - 'ESC key detected! isPaused=1'"
echo "   - 'Toggling pause state to: 0'"
echo "   - Game resumes"
echo ""
echo "5. Test the buttons:"
echo "   - Resume Game: Should unpause"
echo "   - Leave Match: Should return to main menu"
echo "   - Exit Game: Should close the game"
echo ""
echo "Press Enter to start the game..."
read

cd "$(dirname "$0")/build"

echo "Starting game with console output..."
echo "------------------------------------"
./multyPlayer 2>&1 | tee game_test.log

echo ""
echo "------------------------------------"
echo "Game closed."
echo "Console output saved to: build/game_test.log"
echo ""
echo "Check the log for these debug messages:"
echo "  - 'ESC key detected!'"
echo "  - 'Toggling pause state to:'"
echo "  - 'Resume button clicked'"
echo "  - 'Leave Match button clicked'"
echo "  - 'Exit Game button clicked'"
echo "  - 'Stopped room on port XXXX'"
echo "  - 'Left match and returned to main menu'"
